### ISSUE TITLE
ConsistentFormat

### ISSUE THREAD

**Issue by rsryman** [rryman/BB2-Worksheets#2]

**Comment by rsryman** [comment]
Add Acknowledgements
See Github Issue BB1 Issue#3:
1. Use consistent format for the section title: 
**Positions of the Feet** (_Book 1_ Summary p. #/pp. #). 
2. Place each label place above the corresponding BMN clip, followed by a colon only if there is more info, e.g. 1st: flat/demi-pointes/pointes. See BB3 Worksheets p. 4 as a model.
3. Try to keep font size consistent
4. Add solid start/end stave bar line (instead of dashed bar line) as in BB3 from p. 6 to end

**Comment by rsryman** [comment]
√Acknowledgements added to p. 2
√Caption moved above BMN clips pp. 4-8, pp. 16-18, pp. 32-33
√Replaced dashed vertical lines with solid vertical lines at the start/end of empty staves, from p. 36 to end. Robyn to remove vertical lines and "stretch" the empty stave to match the BMN clip where needed.

**Comment by rryman** [comment]
Looks much more consistent. Thank you!

What do you think about moving "R ft fr" etc., on pp. 17-18 to be consistent with other examples?
If you agree, I can make this change in Adobe Illustrator.

**Comment by rryman** [comment]
On p. 2 - the "TM" appears as an "a" in my pdf.
I can change this in Adobe Illustrator if that is easier for you.

**Comment by rsryman** [comment]
I'm having a big problem. Somehow I can't find the MS Word applications or
Worksheet files under Sheepshaver. I've rebooted and tried everything I can
but no success. We're heading out to Jack's Dixieland Jazz now so I'll try
again tomorrow. Sorry.

Sent from my iPad

On Aug 25, 2018, at 11:48 AM, rryman <notifications@github.com> wrote:

On p. 2 - the "TM" appears as an "a" in my pdf.
I can change this in Adobe Illustrator if that is easier for you.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/rryman/BB2-Worksheets/issues/2#issuecomment-415978235>,
or mute the thread

**Comment by rryman** [comment]
Yikes! Sorry to hear that. At least I have the pdfs so at worse I can just do all the editing via Adobe Illustrator.

**Comment by rsryman** [comment]
I should be able to restore files from a May backup but that will take time and effort tomorrow.

**Comment by rsryman** [comment]
Rhonda:
1. p. 2 Added "TM" (Option+2)
2. p. 17: Petite cabriole ouvert devant/derrière on 1 line
3. p. 18: Grande cabriole ouvert devant/derrière on 1 line

[BB2WorksheetsAug26,2018.pdf](https://github.com/rryman/BB2-Worksheets/files/2321801/BB2WorksheetsAug26.2018.pdf)

**Comment by rryman** [comment]
I have downloaded this latest file - BB2WorksheetsAug26,2018.pdf
I will work on it once I have finished BB1 Worksheets.

**Comment by rsryman** [comment]
Updates made to keep BB2 Worksheets consistent with BB1 Worksheets:
[BB2WorksheetsAug30,2018.pdf](https://github.com/rryman/BB2-Worksheets/files/2337838/BB2WorksheetsAug30.2018.pdf)

When Robyn approves the updates and questions below  in **bold**, Rhonda to print pdf for a final proofread before Robyn begins editing BMN in Adobe Illustrator.

p. 5: changed instructions from 10pt to 12pt and adjusted spacing to keep all on same page
p. 6: changed "movement line" to "_movement_ line"
p. 7: updated wording/placement/font size of labels and captions for consistency with p. 6, **OK?**
p. 8: updated wording, line 1: "…shows the height of the foot." (not leg); removed colon after 2 labels
pp. 9-15, 20-30, etc: removed colon after labels
p. 16: delete: "to sign proportions and placement, the spacing of frames along the stave, and" 
p. 17: instructions reworded to highlight new theory, but still some repetition.
**I moved this paragraph to just above the relevant cabriole examples, OK?**
p. 18: instructions reworded to highlight new theory only
p. 21: The "Note…" instruction (I italicized "_contact_ sign" twice) was redundant but important as a reminder, yes? **I moved it to just above the relevant retiré examples, OK?**
p. 27: changed instructions from 10pt to 12pt and adjusted spacing to keep all on same page
p. 31: delete para 1, and join sentences 1 and 2.
p. 32: the title "A Series of 3 Changements" got lost on the page. See updated sentence: "Note how the spacing clarifies variations in timing in the following series of three changements." **OK?**
pp. 32-35: I think we've gone back and forth on this, but I decided to move the relevant note/instruction above the BMN and place captions below it, in 10 pt font.
 **Please let me know if you object.**
p. 34: wording update: para 1 brackets removed; para 2 "…when an action occurs on every half beat…."
p. 36: para 2 updated, since Robyn is removing the start bar line from all empty staves: "Remember to add…."; changed "legato line" to "_legato_ line"
p. 37: in line 1, change "**and**" to "and"

**Comment by rryman** [comment]
- [ ] p. 5: changed instructions from 10pt to 12pt and adjusted spacing to keep all on same page
- [ ] p. 6: changed "movement line" to "movement line"
- [ ] p. 7: updated wording/placement/font size of labels and captions for consistency with p. 6, OK?
- [ ] p. 8: updated wording, line 1: "…shows the height of the foot." (not leg); removed colon after 2 labels
- [ ] pp. 9-15, 20-30, etc: removed colon after labels
- [ ] p. 16: delete: "to sign proportions and placement, the spacing of frames along the stave, and"
- [ ] p. 17: instructions reworded to highlight new theory, but still some repetition.
- [ ] I moved this paragraph to just above the relevant cabriole examples, OK?
- [ ] p. 18: instructions reworded to highlight new theory only
- [ ] p. 21: The "Note…" instruction (I italicized "contact sign" twice) was redundant but important as a reminder, yes? I moved it to just above the relevant retiré examples, OK?
- [ ] p. 27: changed instructions from 10pt to 12pt and adjusted spacing to keep all on same page
- [ ] p. 31: delete para 1, and join sentences 1 and 2.
- [ ] p. 32: the title "A Series of 3 Changements" got lost on the page. See updated sentence: "Note how the spacing clarifies variations in timing in the following series of three changements." OK?
- [ ] pp. 32-35: I think we've gone back and forth on this, but I decided to move the relevant note/instruction above the BMN and place captions below it, in 10 pt font.
- [ ] Please let me know if you object.
- [ ] p. 34: wording update: para 1 brackets removed; para 2 "…when an action occurs on every half beat…."
- [ ] p. 36: para 2 updated, since Robyn is removing the start bar line from all empty staves: "Remember to add…."; changed "legato line" to "legato line"
- [ ] p. 37: in line 1, change "and" to "and"

**Comment by rryman** [comment]
Rhonda to change Copyright to September 2018 on BB2 Worksheets?

**Comment by rryman** [comment]
Page 6 - should I take out the dotted lines in the 2nd example (with the movement lines) to match the ebook page 12?

**Comment by rryman** [comment]
Starting on page 9 - consistency of capitalization of ballet vocabulary?
i.e., Temps Levé, etc. on page 9 and Temps levé devant (Italian), etc. on page 11.

**Comment by rryman** [comment]
Page 16 - how about ...
Copy each frame in the space provided below, paying careful attention to the accurate drawing of
movement lines, jump lines, aerial positions, and turn signs.

**Comment by rryman** [comment]
Page 16 - error?
Coupé sauté **dessus** (under) without aerial position
Should be dessous?

**Comment by rryman** [comment]
Page 17 - error
Changement **batte**/Entrechat royal R ft fr
battu

**Comment by rryman** [comment]
Page 17 - error
Since the aerial position is written in relation to the upright body, the feet are written just above
the floor line when the leg or legs are **are [delete]** extended directly below the body as in entrechats, but just below the knee or hip height when the legs are extended outward as in petite or grande cabriole, respectively. Note that the qualification (in front or behind sign) is centred on the two-feet-together-level sign to show that the feet come together in front of or behind the body.

**Comment by rryman** [comment]
Page 18 notation

In the ebook, in grande cabriole, we decided to make the first leg devant and derriere a little lower to match the aerial position (so it looks like the feet don't drop in the air) and then the ending position a little higher.
Do you want this to be the same in the writing worksheets?

**Comment by rryman** [comment]
Page 19 
I find the spacing of the titles for the turn signs hard to read. Do you have a strong objection to me centering them as they are in the ebook? Also the spacing of the turn signs are off. I believe this sort of change is easier to do in Adobe Illustrator than it is in word.

**Comment by rryman** [comment]
Page 27
When recording jumps with turns, it is particularly important to keep the jump lines shallow
enough to allow room for turn signs below. Keep all below stave information as close to the floor
line as possible, maintaining clarity. **Pay careful attention to the placement of the direction signs and the turn signs.**

I think it wouldn't hurt to also remind them of the placement of the direction and turn signs in relation to jumps. What do you think?

**Comment by rryman** [comment]
Page 27 
Capitalization? Pas **Failli**

**Comment by rryman** [comment]
Page 29
Tour en l'air - in the ebook we have a smaller opening of the leading arm on the aerial position.
Do you want me to make it smaller in the worksheets, or leave it how you have it?

**Comment by rryman** [comment]
Pages 31 - 35
I should take out the starting bar line and the double bar line from each empty stave so they can get used to drawing them in - correct?

**Comment by rryman** [comment]
Page 33
I'd be inclined to delete the "series of three changements (continued)" in the heading. What do you think?

**Comment by rryman** [comment]
Page 33 - typo

Note that when an aerial position is reached on a main count a pulse beat **marke** is written above.
Note also that the final pulse beat marker may be omitted when the spacing is clear.

**Comment by rryman** [comment]
Page 33
Pulse Beats continued (Book 2 pp. 111-**112**):
Technically this is (Book 2 pp. 111-113):

**Comment by rryman** [comment]
Why hyphenate half-beat marker as you don't hyphenate pulse-beat marker?

**Comment by rryman** [comment]
Page 34 second notation example - error
Bar 1 count 4 - incorrect movement lines for arms

**Comment by rryman** [comment]
Page 35 bottom notation example
Shouldn't the dancers' count for 2 be in the intro?

**Comment by rryman** [comment]
Page 35 bottom of page
Delete "From here on, long notation sequences are split over multiple staves." as this information is restated on the top of page 36.

**Comment by rryman** [comment]
Page 37 - for you consideration
How about - 
instead of "You can check answers a) - d) against these solutions:"
take out the notation and say: "See _Book 2_ p. 124 to check your answers."

**Comment by rryman** [comment]
Page 43
Enchaînement with Repeats (Book 2 p. **138**)
Enchaînement with Repeats (Book 2 p. **137-139**)

**Comment by rryman** [comment]
Consistency of use of commas in the names of steps.
See page 11 versus page 12

I prefer them without the commas when the titles are not on one line. What about you?
Once you decide, will you make it consistent on all pages?

**Comment by rryman** [comment]
Page 37 - for your consideration:
As written below, the arms lift from en bas forward to en haut **only on count 4** in example a) and 
**only on count 3** in example b) **and therefore do not require legato lines.** Copy these into the empty stave below (be sure to add double bar lines):

**Comment by rryman** [comment]
Just going through the email Canan sent with feedback on BB2 Worksheets.
Here are things you didn't change that I think we might want to consider.

**Would you consider writing implied centre line on p. 8?**
I think this is a good idea, don't you?

**Canan suggested using superscript for 1st, 2nd, etc., like we did in BB1 Worksheets.**
Are you willing to make this change?

**Comment by rsryman** [comment]
See updated worksheets:
[BB2WorksheetsSept3,2018.pdf](https://github.com/rryman/BB2-Worksheets/files/2346609/BB2WorksheetsSept3.2018.pdf)

**Comment by rryman** [comment]
Page 15

Change Jeté dessus (Italian) to Jeté dessus (over) (Italian)?
or does this look too weird with consecutive bracketed info?

**Comment by rryman** [comment]
I am fine with upper case retained from pp. 38-42 in title of exercise.

**Comment by rryman** [comment]
Not implemented from a previous comment:

What do you think about moving "R ft fr" etc., on pp. 17-18 to below the notation to be consistent with other examples?

If you agree, I can make this change in Adobe Illustrator.

**Comment by rryman** [comment]
Robyn to thicken any basic signs that are superimposed on the stave line and are difficult to see.

**Comment by rryman** [comment]
Page 34 Notation error
First example, Bar 2, Count 1 - Arm movement missing. Should lower to bras bas on the landing of the assemble.

**Comment by rryman** [comment]
[Re: Page 35 bottom notation example (and on page 36)
Shouldn't the dancers' count for 2 be in the intro?]

Rhonda, you added the dancers' count 2 to the intro, but didn't remove it from Bar 2 of the exercise so that it is the same as in Book 2.
This is easy for me to do in Adobe Illustrator if you don't want to bother with MacBenesh.

**Comment by rryman** [comment]
Not that it really matters, but in earlier examples you have used a range of page numbers when the example appears on multiple pages. I thought that as this example introduces signs not covered in BB2 (as it is Next Steps) it might be helpful to give the number range. No problem if you want to keep it as is.

UPDATED: Enchaînement with Repeats (Book 2 p. 139) since the BMN is clearest on that page?

Page 43
Enchaînement with Repeats (Book 2 p. 138)
Enchaînement with Repeats (Book 2 p. 137-139)

**Comment by rryman** [comment]
Rhonda said: PLEASE CLARIFY: We use "implied centre line" on p.8.

By "write" implied centre line, Canan meant "notate" the implied centre line in the examples, which you have now added. So it is all good!

**Comment by rryman** [comment]
Rhonda said: I had to change superscript manually throughout. It seems fine in 12 pt but very small in 10 pt as on p. 9, OK?

I printed out page 9 and I can read it. It is tiny, but still legible. Let's leave it like this for consistency sake.

**Comment by rryman** [comment]
Thanks! I think I am now good to go on editing in Adobe Illustrator using
BB2WorksheetsSept5,2018.pdf
