### ISSUE TITLE
Further Updates

### ISSUE THREAD

**Issue by rryman** [rryman/BB2-Worksheets#3]
Sis, when you have time will you please look at BB2 Worksheets page 9.
There are no examples of 4th opposite 1st, so can we say on line 3 ...

are apart, as in **2nd and 4th opposite 5th positions**, the jump line starts below the centre of the signs?

**Comment by rsryman** [comment]
What about deleting "opposite 1st" and just saying: "…are apart, as in 2nd and 4th positions, the jump line starts below the centre of the signs" ? Or does that cause a change in line break that is hard for you to fix?

**Comment by rryman** [comment]
That will be fine. I'll make it work.

**Comment by rryman** [comment]
**TO DO**
Once Robyn is finished the edits, Rhonda needs to proofread the text at the top of page 9 as I changed it to have parallel structure and it needs to be checked.

**Comment by rsryman** [comment]
Not sure what you mean by parallel structure, so can we discuss this? I
really think line 3 was correct as in the Sept 5 version, even though there
is no example of the line attaching re 4th opposite 1st. Since you objected
I agreed to the more general update, but the final line of para 1 should
definitely stay as is re "4th position opposite 5th."
