### ISSUE TITLE
Add Grey Notation and New Instructions

### ISSUE THREAD

**Issue by rryman** [rryman/BB2-Worksheets#4]
BB2 Worksheets:

- [x] Add new global instructions on BB2 Worksheets page 4.
When grey notation is provided, trace the Benesh signs (not the bar lines and stave lines). Then copy each series ...

Greyed Notation:
- [x] Book 2 p. 9
- [x] Book 2 p. 12
- [x] Book 2 p. 13
- [x] Book 2 pp. 14-15 - Condense instructions if needed to keep all on one page. Move red instructions to previous page for Robyn.
- [x] Book 2 Summary p. 31
- [x] Book 2 Summary p. 37 top stave only
- [x] Book 2 Summary p. 44 3rd stave only (move rond de jambe to next page) and add grey notation
- [x] Book 2 Summary p. 56 jete passe
Rhonda to see what works well for rest of chapter 3.

- [x] Review of Turn Signs (Book 2 p. 66) - instructions
Trace the grey turn signs and then copy each ...
Rhonda to add a line of turn signs is possible.

**Comment by rsryman** [comment]
Re Book 2 pp. 14-15, Worksheets p. 8, I omitted empty spaces but kept all the instructions, since they seemed important. If you find the page too cramped, maybe you can shift the spacing a bit in AI.

Book 2 Summary p. 44, I added a stave for the top example also - because there is room. Also, I took out the page break so that the next examples shift to follow rdj. Then I added an extra copy wherever there was room on the page. If it's too much work for you to grey these out, let me know and I'll remove whatever you decide.

**Comment by rryman** [comment]
These all look good. No problem to grey out what you have added.
